---
title: "NYC Flights Data"
author: "Mia Fitzgerald"
date: "4/16/2026"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = TRUE, message = TRUE)
library(knitr)
library(tidyverse)
library(nycflights13)
library(dplyr)
library(maps)
library(ggplot2)

```


### First 6 Origin/Destination Pairs


```{r}
OD_flights <- flights %>%
  count(origin, dest)

OD_flights %>%
  head(6) %>%
  kable()

```


^[Question 1 complete]


### XLOOKUP and Join Coordinates


```{r}
airports_3 <- airports %>% 
  select(lat, lon, faa) 

OD_flights2 <- OD_flights %>%
  left_join(airports_3, join_by(origin == faa)) %>% 
  rename(origin_lat = lat, origin_lon = lon) %>%
  relocate(origin_lat, origin_lon, .before = dest) 

OD_flights2 %>%
  head(6) %>%
  kable()

```


^[Question 2 complete]


### First 6 Latitude and Longitude of the Destination Airports 


```{r}
OD_flights3 <- OD_flights %>%
  left_join(airports_3, join_by(dest == faa)) %>% 
  rename(dest_lat = lat, dest_lon = lon) %>%
  relocate(dest_lat, dest_lon, .before = n) 

OD_flights3 %>%
  head(6) %>%
  kable()

```


^[Question 3 complete]


### Map of USA


```{r}
ggplot() +
geom_polygon(data = map_data("state"), mapping = aes(x = long, y = lat, group = group), fill = NA, color = "gray") +
coord_fixed(1.3)

```


^[Question 4 complete]


### The Flight Frequency Mapped from NYC


```{r}
OD_all_coords <- OD_flights3 %>%
  left_join(airports_3, join_by(origin == faa)) %>%
  rename(origin_lat = lat, origin_lon = lon) %>%
  relocate(origin_lat, origin_lon, .before = dest)
  
ggplot() +
geom_polygon(data = map_data("state"), mapping = aes(x = long, y = lat, group = group), fill = NA, color = "gray") +
coord_fixed(1.3) +
geom_segment(data = OD_all_coords, mapping = aes(x = origin_lon, y = origin_lat, xend = dest_lon, yend = dest_lat, alpha = n))

```


^[Question 5 complete]


### Filtering out Flights Outside the U.S.


```{r}
OD_all_coords %>% 
  filter(dest_lat > 25 & dest_lat < 50, dest_lon > -125) %>%
ggplot() +
geom_polygon(data = map_data("state"), mapping = aes(x = long, y = lat, group = group), fill = NA, color = "gray") +
coord_fixed(1.3) +
geom_segment(mapping = aes(x = origin_lon, y = origin_lat, xend = dest_lon, yend = dest_lat, alpha = n))

```


^[Question 6 complete]

